
site_name: Visualeasy

repo_name: 'fga-eps-mds/ 2022-1-Squad7'
repo_url: 'https://github.com/fga-eps-mds/2022-1-Squad7'

nav:
  - Home: 
    - Visualeasy: index.md
  - Documentação:
      - Protótipo de Baixa Fidelidade: documentacao/prot-baixa.md
      - Protótipo de Alta Fidelidade: documentacao/prot-alta.md
      - Custo do Projeto: documentacao/custo.md
      - Riscos do Projeto: documentacao/risco.md
  - Visão de produto:
        - Lean Inception: visao-produto/personas.md
  - Documentação do Projeto:
      - Custo do Projeto: documentacao/custo.md
      - Protótipos de Baixa Fidelidade: documentacao/prot-baixa.md
      - Identidade Visual: documentacao/id-visual.md
      - Protótipo de Alta Fidelidade: documentacao/prot-alta.md
  - Sprints:
    - Modelo de Resumo das Sprints: scrum/modelo-resumo-sprint.md
  - Políticas do Projeto:
    - Padrão da Wiki: politicas/padrao-wiki.md
    - Política de Branch: politicas/politica_de_branch.md
    - Política de Commits: politicas/politica_de_commits.md
    - Código de Conduta: politicas/CODE_OF_CONDUCT.md
    - Guia de Contribuição: politicas/Contributor's_Guide.md
    - Política de Issues: politicas/politica_de_issues.md
    - Política de Pull Requests: politicas/politica_de_pull_request.md
  - Atas de reunião: 
    - Reuniões de equipe: Atas/atas_reuniao_equipe.md
    # - Ata 1: Atas/r1-equipe.md
    # - Ata 2: Atas/r2-equipe.md
    # - Ata 3: Atas/r3-equipe.md
    # - Ata 4: Atas/r4-equipe.md
    # - Ata 5: Atas/r5-equipe.md
    # - Ata 6: Atas/r6-equipe.md
    # - Ata 7: Atas/r7-equipe.md   
    # - Ata 8: Atas/r8-equipe.md   
    # - Ata 9: Atas/r9-equipe.md
    # - Ata 10: Atas/r10-equipe.md
    - Reuniões com POs: Atas/atas_reuniao_pos.md
    # - Ata 2: Atas/r2-pos.md
    # - Ata 3: Atas/r3-pos.md
    # - Ata 4: Atas/r4-pos.md
theme:
  name: "material"
  font:
    text: Sora
  palette:
    primary: "blue"
    accent: "#00D899"
  language: pt
  logo: Imagens/Icon.png
  favicon: Imagens/Icon.png
  icon:
    repo: fontawesome/brands/github


  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    #- navigation.expand
    #- navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fga-eps-mds/2022-1-Squad7

# plugins:
#   - search
#   - awesome-pages

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      options:
        custom_icons:
          - overrides/.icons
