
site_name: Visualeasy

repo_name: 'fga-eps-mds/ 2022-1-Squad7'
repo_url: 'https://github.com/fga-eps-mds/2022-1-Squad7'

nav:
  - Home: 
    - Visualeasy: index.md
  - Visão de produto:
        - Lean Inception: visao-produto/lean-inception.md
        - Visão de Produto: visao-produto/visao-prod.md
        - O produto É - NÃO É - FAZ - NÃO FAZ: visao-produto/e-nao-e.md
        - Objetivos de Negócio: visao-produto/objetivos-negocio.md
        - Personas: visao-produto/personas.md
        - Jornada do Usuário: visao-produto/jornada.md
        - Brainstorming de Funcionalidades: visao-produto/brainstorming.md
        - Revisão Técnica, de Negócio e UX: visao-produto/revisao.md
        - Sequenciador: visao-produto/sequenciador.md
        - MVP Canvas: visao-produto/mvp.md
  - Product Backlog: documentacao/backlog.md
  - Arquitetura e Qualidade:
    - Arquitetura do Projeto: documentacao/arquitetura.md
    - Qualidade do Projeto: documentacao/qualidade.md
    - Relatório de resultados dos formulários de validação das Histórias de Usuário (USs): documentacao/relatorio-qualidade.md
  - Custo e Riscos:
      - Custo do Projeto: documentacao/custo.md
      - Riscos do Projeto: documentacao/risco.md
  - Visual:
      - Protótipos de Baixa Fidelidade: documentacao/prot-baixa.md
      - Identidade Visual: documentacao/id-visual.md
      - Protótipo de Alta Fidelidade: documentacao/prot-alta.md
  - Organização:
    - Termo de Abertura de Projeto: documentacao/tap.md
    - Plano de Comunicação: documentacao/plano-comunicacao.md
    - Quadro de conhecimentos: documentacao/quadro-conhecimento.md
    - Metodologias: documentacao/metodologias.md
  - Sprints:
    - Modelo de Resumo para Sprints: scrum/modelo-resumo-sprint.md
    - Sprint 0: scrum/sprint0.md
    - Sprint 1: scrum/sprint1.md
    - Sprint 2: scrum/sprint2.md
    - Sprint 3: scrum/sprint3.md
    - Sprint 4: scrum/sprint4.md
    - Sprint 5: scrum/sprint5.md
    - Sprint 6: scrum/sprint6.md
    - Velocity: scrum/velocity.md
  - Políticas:
    - Padrão da Wiki: politicas/padrao-wiki.md
    - Política de Branch: politicas/politica_de_branch.md
    - Política de Commits: politicas/politica_de_commits.md
    - Código de Conduta: politicas/CODE_OF_CONDUCT.md
    - Guia de Contribuição: politicas/Contributor's_Guide.md
    - Politíca de Histórias de Usuário: politicas/politica_de_US.md
    - Política de Issues: politicas/politica_de_issues.md
    - Política de Melhoria: politicas/politica_de_melhoria.md
    - Política de Pull Requests: politicas/politica_de_pull_request.md
  - Atas de reunião: 
    - Reuniões de equipe: Atas/atas_reuniao_equipe.md
    - Reuniões com POs: Atas/atas_reuniao_pos.md

theme:
  name: "material"
  font:
    text: Sora
  palette:
    primary: "red"
    accent: "red"
  language: pt
  logo: Imagens/Icon.png
  favicon: Imagens/Icon.png
  icon:
    repo: fontawesome/brands/github


  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    #- navigation.expand
    #- navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fga-eps-mds/2022-1-Squad7

# plugins:
#   - search
#   - awesome-pages

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      options:
        custom_icons:
          - overrides/.icons
